### ISSUE TITLE
Баги

### ISSUE THREAD

**Issue by umifi** [U61vashka/MC-Auth-with-VK#1]
Здравствуй. Установил плагин и нашел несколько багов: 

Баг #1:
При привязке VK к аккаунту, то VK ID вписывается не в ту строку в Mysql таблице.
![image](https://user-images.githubusercontent.com/48959361/127773605-ba016261-ba7b-4877-9749-fdfcb7706f2c.png)

Баг #2:
При использовании команды "/помощь" в ЛС группы, пишет что такой команды нету.
![image](https://user-images.githubusercontent.com/48959361/127773636-aefe08be-4e5d-4510-8fe2-8f31db2ead99.png)

**Comment by umifi** [comment]
И видимо из-за того что ID вписывается не туда, то аккаунты не отображаются в вк.
![image](https://user-images.githubusercontent.com/48959361/127773825-57db9a45-b508-4873-8c90-12f54ed453bb.png)

**Comment by umifi** [comment]
Используя админ-панель оно вечно грузится, и ничего не выводит
![image](https://user-images.githubusercontent.com/48959361/127774549-b2802b4e-5052-4068-827c-43ac4e7f180c.png)

А в консоли иногда пишется 
`15:53:45 [WARNING] Event VKMessageEvent took 266,202,541ns to process for public void me.mastercapexd.auth.vk.commandhandler.VKCommandHandler.onVKMessage(com.ubivashka.vk.bungee.events.VKMessageEvent)!`
Как я понимаю это из-за того что оно грузит и ничего не показывает

**Comment by umifi** [comment]
А при выходе игрока с сервера пишет ошибку в консоли: 
![image](https://user-images.githubusercontent.com/48959361/127774584-16d96281-5c15-4922-8315-810d9af90483.png)

`16:22:43 [INFO] [umifi] <-> DownstreamBridge <-> [survival1] has disconnected
16:22:43 [SEVERE] com.mysql.jdbc.MysqlDataTruncation: Data truncation: Out of range value for column 'vkId' at row 1
16:22:43 [SEVERE]     at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3931)
16:22:43 [SEVERE]     at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
16:22:43 [SEVERE]     at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
16:22:43 [SEVERE]     at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
16:22:43 [SEVERE]     at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
16:22:43 [SEVERE]     at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1915)
16:22:43 [SEVERE]     at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1254)
16:22:43 [SEVERE]     at me.mastercapexd.auth.storage.sql.SQLAccountStorage.updateAccount(SQLAccountStorage.java:70)
16:22:43 [SEVERE]     at me.mastercapexd.auth.storage.sql.SQLAccountStorage.lambda$saveOrUpdateAccount$0(SQLAccountStorage.java:119)
16:22:43 [SEVERE]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
16:22:43 [SEVERE]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
16:22:43 [SEVERE]     at java.lang.Thread.run(Thread.java:748)`

**Comment by U61vashka** [comment]
> Баг #4:
> Используя админ-панель оно вечно грузится, и ничего не выводит
> ![image](https://user-images.githubusercontent.com/48959361/127774549-b2802b4e-5052-4068-827c-43ac4e7f180c.png)
> 
> А в консоли иногда пишется
> `15:53:45 [WARNING] Event VKMessageEvent took 266,202,541ns to process for public void me.mastercapexd.auth.vk.commandhandler.VKCommandHandler.onVKMessage(com.ubivashka.vk.bungee.events.VKMessageEvent)!`
> Как я понимаю это из-за того что оно грузит и ничего не показывает

Включи в LongpoolAPI события связанные с кнопками

**Comment by U61vashka** [comment]
> Баг #5:
> А при выходе игрока с сервера пишет ошибку в консоли:
> ![image](https://user-images.githubusercontent.com/48959361/127774584-16d96281-5c15-4922-8315-810d9af90483.png)
> 
> `16:22:43 [INFO] [umifi] <-> DownstreamBridge <-> [survival1] has disconnected 16:22:43 [SEVERE] com.mysql.jdbc.MysqlDataTruncation: Data truncation: Out of range value for column 'vkId' at row 1 16:22:43 [SEVERE] at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3931) 16:22:43 [SEVERE] at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869) 16:22:43 [SEVERE] at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524) 16:22:43 [SEVERE] at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675) 16:22:43 [SEVERE] at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465) 16:22:43 [SEVERE] at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1915) 16:22:43 [SEVERE] at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1254) 16:22:43 [SEVERE] at me.mastercapexd.auth.storage.sql.SQLAccountStorage.updateAccount(SQLAccountStorage.java:70) 16:22:43 [SEVERE] at me.mastercapexd.auth.storage.sql.SQLAccountStorage.lambda$saveOrUpdateAccount$0(SQLAccountStorage.java:119) 16:22:43 [SEVERE] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 16:22:43 [SEVERE] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 16:22:43 [SEVERE] at java.lang.Thread.run(Thread.java:748)`



> Баг #3:
> И видимо из-за того что ID вписывается не туда, то аккаунты не отображаются в вк.
> ![image](https://user-images.githubusercontent.com/48959361/127773825-57db9a45-b508-4873-8c90-12f54ed453bb.png)



> Здравствуй. Установил плагин и нашел несколько багов:
> 
> Баг #1:
> При привязке VK к аккаунту, то VK ID вписывается не в ту строку в Mysql таблице.
> ![image](https://user-images.githubusercontent.com/48959361/127773605-ba016261-ba7b-4877-9749-fdfcb7706f2c.png)
> 
> Баг #2:
> При использовании команды "/помощь" в ЛС группы, пишет что такой команды нету.
> ![image](https://user-images.githubusercontent.com/48959361/127773636-aefe08be-4e5d-4510-8fe2-8f31db2ead99.png)

Исправил в последнем обновлении

**Comment by U61vashka** [comment]
Насчёт бага #2 добавь в конфиг свою команду
![image](https://user-images.githubusercontent.com/85439143/127780358-75598538-7077-4c12-b3ac-296520894c19.png)

**Comment by umifi** [comment]
1) Добавил команду как вы сказали, но почему-то всё равно не отображает.

![image](https://user-images.githubusercontent.com/48959361/127781202-a3c65fbc-253c-4508-9941-cc6128559566.png)
![image](https://user-images.githubusercontent.com/48959361/127781218-9d235d8e-7ad6-46d4-9603-ed0a966b2e76.png)


2) По поводу кнопок (бага 4), всё работает когда дал право, но после нажатия и после того как оно отобразило информацию, загрузка которая отображается в самой кнопке не пропадает. Это наверное не критично, но всё равно.


3) По поводу ID, да, спасибо, всё заработало!

**Comment by U61vashka** [comment]
> 1. Добавил команду как вы сказали, но почему-то всё равно не отображает.
> 
> ![image](https://user-images.githubusercontent.com/48959361/127781202-a3c65fbc-253c-4508-9941-cc6128559566.png)
> ![image](https://user-images.githubusercontent.com/48959361/127781218-9d235d8e-7ad6-46d4-9603-ed0a966b2e76.png)
> 
> 1. По поводу кнопок (бага 4), всё работает когда дал право, но после нажатия и после того как оно отобразило информацию, загрузка которая отображается в самой кнопке не пропадает. Это наверное не критично, но всё равно.
> 2. По поводу ID, да, спасибо, всё заработало!

![image](https://user-images.githubusercontent.com/85439143/127804131-2d5a457b-71a4-47cf-bbaf-d64c4e2b7764.png)
Добавьте еще в "фильтр" regex свою команду

**Comment by umifi** [comment]
Благодарю! Всё работает.

**Comment by umifi** [comment]
![image](https://user-images.githubusercontent.com/48959361/127846958-ccbc0ea7-eb0a-43f5-8683-2d6718b6d707.png)
Иногда пишется данное предупреждение в консоли. Из-за чего оно может быть связано?

**Comment by U61vashka** [comment]
> ![image](https://user-images.githubusercontent.com/48959361/127846958-ccbc0ea7-eb0a-43f5-8683-2d6718b6d707.png)
> Иногда пишется данное предупреждение в консоли. Из-за чего оно может быть связано?

Это уже баг со стороны VK-API, так как я разработчик VK-API, то скорее всего пофикшу скоро это. На самом деле это даже не баг, дело в том что иногда ивент долго обрабатывается и думаю как то сделать асинхронно(но сомневаюсь что это возможно в банже) ивенты во избежания такого

**Comment by U61vashka** [comment]
> Благодарю! Всё работает.

Рад этой информации
