### ISSUE TITLE
Предложения для плагина

### ISSUE THREAD

**Issue by umifi** [U61vashka/MC-Auth-with-VK#2]
1. Я заметил что у бота есть команды "/принять" и "/отклонить" но они, как я вижу, не используются потому что нету команды для включения подтверждения входа. Предлагаю добавить команду "/2фа" для включения подтверждения входа через ВКонтакте.

2. Предлагаю добавить уведомления о входе игрока, а также к этому сообщению прикреплять кнопки Принять или Отклонить если включена 2ФА авторизация. А если аккаунт не привязан, то будут кнопки Кикнуть или Заблокировать.

3. Добавить возможность заблокировать аккаунт командой "/заблокировать", а для разблокировки "/разблокировать".

4. Добавить команду "/статус" которая будет выводить информацию об аккаунте (включена ли 2ФА, онлайн ли аккаунт и тому прочее)

5. Также было бы неплохо добавить больше команд для админки, например сменить пароль юзеру, либо заблокировать, кикнуть его. Ну и починить отображение аккаунтов в админке, а то там пишется "Ваши аккаунты:" при нажатии на все аккаунты и все привязанные аккаунты.

_Буду готов пожертвовать в проект если появятся данные функции и дальнейшее развитие проекта добавление функций которые нигде нету._

**Comment by U61vashka** [comment]
> 1. Я заметил что у бота есть команды "/принять" и "/отклонить" но они, как я вижу, не используются потому что нету команды для включения подтверждения входа. Предлагаю добавить команду "/2фа" для включения подтверждения входа через ВКонтакте.
> 2. Предлагаю добавить уведомления о входе игрока, а также к этому сообщению прикреплять кнопки Принять или Отклонить если включена 2ФА авторизация. А если аккаунт не привязан, то будут кнопки Кикнуть или Заблокировать.
> 3. Добавить возможность заблокировать аккаунт командой "/заблокировать", а для разблокировки "/разблокировать".
> 4. Добавить команду "/статус" которая будет выводить информацию об аккаунте (включена ли 2ФА, онлайн ли аккаунт и тому прочее)
> 5. Также было бы неплохо добавить больше команд для админки, например сменить пароль юзеру, либо заблокировать, кикнуть его. Ну и починить отображение аккаунтов в админке, а то там пишется "Ваши аккаунты:" при нажатии на все аккаунты и все привязанные аккаунты.
> 
> _Буду готов пожертвовать в проект если появятся данные функции и дальнейшее развитие проекта добавление функций которые нигде нету._

1. 2 факторная аутентификация уже есть, и она по дефолту включена (нельзя выключить), думаю в скором будущем добавлю
2. Сообщения о входе и т.д. В плагине уже имеются, не понял насчёт кнопок кикнуть восстановить ибо если аккаунт не привязан, куда отправлять сообщения?
3. Да думаю сделаю такую фичу для админов
4. Я уже подумывал об этом скоро будет если успею
5. Админ и так уже может Сбрасывать пароли, кикать и так далее через админ пароль, а смена пароля происходит через /пароль ник новыйПароль.

Я думаю сделать вики, потому что много кто не разбирается в плагине 

Насчёт поддержки очень буду рад, в странице спигота скоро появится ссылка на мой киви

**Comment by umifi** [comment]
1. Мне почему-то не приходят уведомления для подтверждения входа, хотя аккаунт привязан.
2. Сообщения о входе тоже не приходят, хотя аккаунт привязан.
3. Не обязательно для админов. Ее можно и для игрока, если вдруг игрок сомневается в своем пароле и хочет чтобы никто не заходил.
4. Супер!
5. А, я думал смена пароля только для юзера который привязал. Тогда ноу проблем!

За вики буду очень рад. Чтобы прочитать все возможности плагина, а то вдруг что-то где-то не сказано в конфиге или я не заметил.

**Comment by U61vashka** [comment]
> 1. Мне почему-то не приходят уведомления для подтверждения входа, хотя аккаунт привязан.
> 2. Сообщения о входе тоже не приходят, хотя аккаунт привязан.
> 3. Не обязательно для админов. Ее можно и для игрока, если вдруг игрок сомневается в своем пароле и хочет чтобы никто не заходил.
> 4. Супер!
> 5. А, я думал смена пароля только для юзера который привязал. Тогда ноу проблем!
> 
> За вики буду очень рад. Чтобы прочитать все возможности плагина, а то вдруг что-то где-то не сказано в конфиге или я не заметил.

Насчёт отсутствия сообщений при входе, у тебя все сообщения в кфг на месте? Новая ли версия стоит, и да, если у тебя сессия, сообщение о входе только при ее отсутствии

**Comment by umifi** [comment]
> Насчёт отсутствия сообщений при входе, у тебя все сообщения в кфг на месте? Новая ли версия стоит, и да, если у тебя сессия сообщение о входе только при ее отсутствии

Аааа, там еще сессия не должна быть активна. Тогда всё работает. 😉

**Comment by Pazi775** [comment]
1) Сделать команды для консоли.
По типу:
 Auth reload- перезапуск плагина.
Auth prelogin- авторизация игрока без пароля.
Auth info[nick] - выдаёт информацию:1)когда последний раз заходил 2)Всё ip. С которых, заходил. 3)пароль 4) Страна праживания. Ну и что-то ещё.
Пока всё.
